server:
  port: 9527
spring:
  application:
    name: springcloud-study-zuul-gateway

eureka:
  instance:
    instance-id: gateway-9572
    prefer-ip-address: true
  client:
    service-url:
      # 单机版配置defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka #设置与eureka server 交互的地址查询服务和注册服务都需要依赖的地址
      #集群配置
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

info:
  app.name: springcloud-study-zuul-gateway
  company.name: com.ly.springcloud
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}



#路由访问映射规则
zuul:
  routes:
    mydept.serviceId: microservicecloudproviderdept
    mydept.path: /mydept/*      #配置虚拟的路径映射
    #多个用"*" ignored-services: "*"
  ignored-services: microservicecloudproviderdept       #为了保证路径访问的统一性将真实的路径进行忽略
  #公共前缀
  prefix: /springcloud


  ratelimit:
      key-prefix: mydept #请求的key的前缀
      enabled: true
      behind-proxy: true #代理之后
      default-policy: #针对所有的路由配置的策略
        limit: 10 #请求数量限制
        quota: 1000 #请求时间限制（毫秒）
        refresh-interval: 60 # 刷新时间窗口的时间
        type:  #可选 限流方式
          - user
          - origin
          - url